from typing import Protocol

from domain.indexing import IndexHealth, IndexJob, IndexedDocument


class IndexRepository(Protocol):
    def enqueue(self, job: IndexJob) -> None: ...

    def next_pending(self, vault_id: str) -> IndexJob | None: ...

    def save_job(self, job: IndexJob) -> None: ...

    def retry_failed(self, vault_id: str) -> IndexJob | None: ...

    def recover_running(self, vault_id: str) -> None: ...

    def current_documents(self, vault_id: str) -> list[IndexedDocument]: ...

    def documents(self, vault_id: str) -> list[IndexedDocument]: ...

    def save_document(self, document: IndexedDocument) -> None: ...

    def invalidate_current_path(self, vault_id: str, relative_path: str, reason: str) -> None: ...

    def resolve_pending_association(self, vault_id: str, relative_path: str, resolution: str) -> None: ...

    def health(self, vault_id: str) -> IndexHealth: ...
