from typing import Protocol

from domain.graph_projection import DurableGraphProjection, GraphProjectionKey
from domain.indexing import IndexBlockBackfillReport, IndexHealth, IndexJob, IndexedDocument


class IndexRepository(Protocol):
    def enqueue(self, job: IndexJob) -> None: ...

    def next_pending(self, vault_id: str) -> IndexJob | None: ...

    def save_job(self, job: IndexJob) -> None: ...

    def retry_failed(self, vault_id: str) -> IndexJob | None: ...

    def recover_running(self, vault_id: str) -> None: ...

    def current_documents(self, vault_id: str) -> list[IndexedDocument]: ...

    def documents(self, vault_id: str) -> list[IndexedDocument]: ...

    def backfill_current_blocks(self, vault_id: str) -> IndexBlockBackfillReport: ...

    def save_document(self, document: IndexedDocument) -> None: ...

    def save_committed_unit(
        self,
        documents: tuple[IndexedDocument, ...],
        invalidations: tuple[tuple[str, str, str], ...],
        projection: DurableGraphProjection | None,
    ) -> None: ...

    def get_graph_projection(self, key: GraphProjectionKey) -> DurableGraphProjection | None: ...

    def invalidate_current_path(self, vault_id: str, relative_path: str, reason: str) -> None: ...

    def resolve_pending_association(self, vault_id: str, relative_path: str, resolution: str) -> None: ...

    def health(self, vault_id: str) -> IndexHealth: ...
