from typing import Protocol

from domain.providers import ModelSelection, Provider


class ProviderRepository(Protocol):
    def save(self, provider: Provider) -> None: ...

    def get(self, provider_id: str) -> Provider: ...

    def list(self) -> list[Provider]: ...

    def delete(self, provider_id: str) -> None: ...

    def get_default(self, model_type: str) -> ModelSelection | None: ...

    def save_default(self, selection: ModelSelection) -> None: ...

    def delete_default(self, model_type: str) -> None: ...
