from __future__ import annotations

from typing import Protocol

from domain.tasks import ImportTask, ImportTaskEvent, ImportTaskItem
from domain.classification import ClassificationSuggestion
from domain.derived_notes import NoteProposal
from domain.evidence import (
    ConversionAttempt,
    ConversionEvidence,
    EvidenceLocator,
    OcrEvidence,
    OcrTarget,
    ParseEvidence,
)
from domain.review_commits import CommitJournal, ReviewDecision, ReviewSnapshot


class TaskRepository(Protocol):
    def create(self, task: ImportTask, event_type: str) -> None: ...

    def get(self, task_id: str) -> ImportTask: ...

    def list(self) -> list[ImportTask]: ...

    def save(self, task: ImportTask, event_type: str) -> None: ...

    def delete(self, task_id: str) -> None: ...

    def append_item(self, task_id: str, item: ImportTaskItem) -> ImportTask: ...

    def clear_items(self, task: ImportTask, event_type: str) -> None: ...

    def list_items(self, task_id: str) -> list[ImportTaskItem]: ...

    def events_after(self, task_id: str, event_id: int) -> list[ImportTaskEvent]: ...

    def latest_event_id(self, task_id: str) -> int: ...

    def recover_interrupted_tasks(self) -> list[ImportTask]: ...

    def record_parse_evidence(self, item_id: int, evidence: ParseEvidence) -> ImportTask: ...

    def get_parse_evidence(self, item_id: int) -> ParseEvidence | None: ...

    def find_parse_evidence(
        self, vault_id: str, source_id: str, content_sha256: str
    ) -> ParseEvidence | None: ...

    def record_conversion_attempt(self, attempt: ConversionAttempt) -> ConversionAttempt: ...

    def record_conversion_evidence(self, item_id: int, evidence: ConversionEvidence) -> ImportTask: ...

    def get_conversion_evidence(self, item_id: int) -> ConversionEvidence | None: ...

    def list_conversion_attempts(self, item_id: int) -> tuple[ConversionAttempt, ...]: ...

    def record_conversion_rejection(self, item_id: int, reason: str) -> ImportTask: ...

    def record_parse_failure(
        self, item_id: int, reason: str, locator_summary: str | None = None
    ) -> ImportTask: ...

    def record_ocr_started(self, item_id: int, target: OcrTarget) -> ImportTask: ...

    def record_ocr_evidence(self, item_id: int, evidence: OcrEvidence) -> ImportTask: ...

    def record_ocr_attempt_failure(
        self, item_id: int, target: OcrTarget, engine: str, reason: str, raw_result: str = ""
    ) -> ImportTask: ...

    def record_ocr_failure(self, item_id: int, target: OcrTarget, reason: str) -> ImportTask: ...

    def record_ocr_not_required(self, item_id: int) -> ImportTask: ...

    def apply_ocr_decision(
        self,
        item_id: int,
        target_id: str,
        decision: str,
        reason: str,
        corrected_text: str | None = None,
    ) -> ImportTask: ...

    def get_ocr_target(self, item_id: int, target_id: str) -> OcrTarget: ...

    def record_note_proposal(self, item_id: int, proposal: NoteProposal) -> ImportTask: ...

    def get_note_proposal(self, item_id: int) -> NoteProposal | None: ...

    def list_note_proposals(self, task_id: str) -> list[NoteProposal]: ...

    def invalidate_note_proposals(self, task_id: str, item_id: int) -> None: ...

    def record_classification_suggestion(
        self, item_id: int, suggestion: ClassificationSuggestion, event_type: str
    ) -> ImportTask: ...

    def record_classification_revision(
        self, item_id: int, proposal: NoteProposal, suggestion: ClassificationSuggestion
    ) -> ImportTask: ...

    def get_classification_suggestion(self, item_id: int) -> ClassificationSuggestion | None: ...

    def list_classification_suggestions(self, task_id: str) -> list[ClassificationSuggestion]: ...

    def get_ocr_corrections(self, item_id: int) -> tuple[tuple[EvidenceLocator, str], ...]: ...

    def record_review_snapshot(self, snapshot: ReviewSnapshot, event_type: str) -> None: ...

    def get_review_snapshot(self, task_id: str) -> ReviewSnapshot | None: ...

    def record_review_decision(self, decision: ReviewDecision, event_type: str) -> None: ...

    def get_review_decision(
        self, task_id: str, review_item_id: str
    ) -> ReviewDecision | None: ...

    def record_commit_journal(self, journal: CommitJournal, event_type: str) -> None: ...

    def list_commit_journals(self, task_id: str) -> list[CommitJournal]: ...
