from typing import Protocol

from domain.policies import ExclusionRule, VaultPolicy
from domain.vaults import Vault


class VaultPolicyRepository(Protocol):
    def create_vault_with_default_policy(self, vault: Vault) -> None: ...

    def save_vault_and_bump_policy(self, vault: Vault) -> None: ...

    def delete_vault_and_policy(self, vault_id: str) -> None: ...

    def ensure_policy(self, vault_id: str, updated_at: str) -> VaultPolicy: ...

    def get_policy(self, vault_id: str) -> VaultPolicy: ...

    def save_policy(self, policy: VaultPolicy) -> None: ...

    def bump_policy_revision(self, vault_id: str, updated_at: str) -> VaultPolicy: ...

    def list_rules(self, vault_id: str) -> list[ExclusionRule]: ...

    def save_rule(self, rule: ExclusionRule) -> None: ...

    def create_rule_and_bump(self, rule: ExclusionRule) -> VaultPolicy: ...

    def update_rule_and_bump(self, rule: ExclusionRule) -> VaultPolicy: ...

    def delete_rule(self, vault_id: str, rule_id: str) -> None: ...

    def delete_rule_and_bump(
        self, vault_id: str, rule_id: str, updated_at: str
    ) -> VaultPolicy: ...
